---
title: "Schedule"
subtitle: "ENVS 3030 | Environmental Health | Spring 2026"
format: 
  html:
    toc-expand: true
tbl-colwidths: [20,20,60]
---

## Introduction

### Week 1

Total pages of reading: 17

+---------------------------+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**                  | **Topic**                     | **Readings & Assignments**                                                                                                                                                          |
+---------------------------+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, January 12**    | Course Intro                  | -   [**Read**]{.underline}***:*** Cloud, John. 2009. “Study: Doodling Helps You Pay Attention.” <https://time.com/archive/6933247/study-doodling-helps-you-pay-attention/>          |
|                           |                               | -   [**Read**]{.underline}***:*** Morris, Giles. 2009. “If you only do one thing this week, avoid multitasking.” <https://www.theguardian.com/money/2009/oct/05/avoid-multitasking> |
+---------------------------+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, January 14** | Intro to Environmental Health | -   [**Read**]{.underline}: Frumkin, Chapter 1+ **clicker quiz**                                                                                                                    |
|                           |                               |     -   Print: pp. 3-20                                                                                                                                                             |
|                           |                               |     -   PDF: pp. 45-61                                                                                                                                                              |
+---------------------------+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recitation**            | TBD                           | -   Choose work groups                                                                                                                                                              |
+---------------------------+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

## Part 1: Environmental Exposures in Daily Life

### Week 2

+---------------------------+---------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| **Monday, January 19**    | No class - Martin Luther King Jr. day | -   None                                                                                                        |
+---------------------------+---------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| **Wednesday, January 21** | Exposure Science                      | -   [**Read:**]{.underline} Frumkin, Chapter 8 + **clicker quiz**                                               |
|                           |                                       |     -   Print: pp. 181-196                                                                                      |
|                           |                                       |     -   PDF: pp. 207-220                                                                                        |
+---------------------------+---------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| **Recitation**            | Intro to Diary Studies                | -   [**Read**]{.underline}**:** Radcliffe & Spencer, Chapter 1. "An Introduction to Qualitative Diary Methods." |
+---------------------------+---------------------------------------+-----------------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 3

+---------------------------+----------------------+------------------------------------------------------------------------+
| **Monday, January 26**    | Buildings & Health   | -   [**Read**]{.underline}**:** Frumkin, Chapter 20 + **clicker quiz** |
|                           |                      |     -   Print: pp. 539-568                                             |
|                           |                      |     -   PDF: pp. 542-569                                               |
+---------------------------+----------------------+------------------------------------------------------------------------+
| **Wednesday, January 28** | Buildings & Health   |                                                                        |
+---------------------------+----------------------+------------------------------------------------------------------------+
| **Recitation**            | Endocrine Disruptors | -   [**Read:**]{.underline} Frumkin, Text Box 6.4                      |
|                           |                      |     -   Print: pp. 132-133                                             |
|                           |                      |     -   PDF: pp. 165-166                                               |
|                           |                      | -   checkED activity (in class): <https://de.check-ed.eu/en/>          |
+---------------------------+----------------------+------------------------------------------------------------------------+

: {.hover}

### Week 4

+---------------------------+----------------+--------------------------------------------------------------------+
| **Monday, February 2**    | Nature Contact | -   [**Read:**]{.underline} Frumkin, Chapter 25 + **clicker quiz** |
|                           |                |     -   Print: pp. 693-712                                         |
|                           |                |     -   PDF: 686-704                                               |
|                           |                | -   [**Begin**]{.underline} Diary Study entries (7 days)           |
+---------------------------+----------------+--------------------------------------------------------------------+
| **Wednesday, February 4** | Pesticides     | -   [**Read:**]{.underline} Frumkin, Chapter 18 + **clicker quiz** |
|                           |                |     -   Print: pp. 477-496                                         |
|                           |                |     -   PDF: pp. 483-501                                           |
+---------------------------+----------------+--------------------------------------------------------------------+
| **Recitation**            | TBD            |                                                                    |
+---------------------------+----------------+--------------------------------------------------------------------+

: {.hover}

### Week 5

+----------------------------+-----------------------+---------------------------------------------------------------------------------------------+
| **Monday, February 9**     | Environmental Justice | -   [**Read:**]{.underline} Frumkin, Chapter 11 **+ clicker quiz**                          |
|                            |                       |     -   Print: pp. 251-266                                                                  |
|                            |                       |     -   PDF: pp. 267-282                                                                    |
|                            |                       | -   [**End**]{.underline} Diary study entries                                               |
+----------------------------+-----------------------+---------------------------------------------------------------------------------------------+
| **Wednesday, February 11** | TBD                   |                                                                                             |
+----------------------------+-----------------------+---------------------------------------------------------------------------------------------+
| **Recitation**             | Diary Study Analysis  | -   [**Read**]{.underline}**:** Radcliffe & Spencer, Chapter 6. "Analyzing Data from QDMs." |
|                            |                       | -   [**Due Friday Feb 13 \@ 5:00 pm:**]{.underline} Diary study individual reflection       |
+----------------------------+-----------------------+---------------------------------------------------------------------------------------------+

: {.hover}

### Week 6

+----------------------------+--------------------+---------------------------------------------------------------------------------+
| **Monday, February 16**    | Risk Communication | -   Read: Frumkin, Chapter 28 + **clicker quiz**                                |
|                            |                    |     -   Print: pp. 769-786                                                      |
|                            |                    |     -   PDF: pp. 756-770                                                        |
+----------------------------+--------------------+---------------------------------------------------------------------------------+
| **Wednesday, February 18** | TBD                |                                                                                 |
+----------------------------+--------------------+---------------------------------------------------------------------------------+
| **Recitation**             | TBD                | -   [**Due Friday Feb 20 \@ 5:00 pm**]{.underline}: Diary study group synthesis |
+----------------------------+--------------------+---------------------------------------------------------------------------------+

: {.hover}

## Part 2: Environmental Health Systems

### Week 7

+----------------------------+--------------------------------+-------------------------------------------------+
| **Monday, February 23**    | Ecology and Ecosystem Services | -   Read: Frumkin, Chapter 2 + **clicker quiz** |
|                            |                                |     -   Print: pp. 27-49                        |
|                            |                                |     -   PDF: pp. 68-89                          |
+----------------------------+--------------------------------+-------------------------------------------------+
| **Wednesday, February 25** | Ecology & Ecosystem Services   |                                                 |
+----------------------------+--------------------------------+-------------------------------------------------+
| **Recitation**             | TBD                            |                                                 |
+----------------------------+--------------------------------+-------------------------------------------------+

: {.hover}

### Week 8

+------------------------+---------------+--------------------------------------------------------------------+
| **Monday, March 2**    | Air Pollution | -   [**Read:**]{.underline} Frumkin, Chapter 13 + **clicker quiz** |
|                        |               |     -   Print: pp. 319-339                                         |
|                        |               |     -   PDF: pp. 332-350                                           |
+------------------------+---------------+--------------------------------------------------------------------+
| **Wednesday, March 4** | Air Pollution |                                                                    |
+------------------------+---------------+--------------------------------------------------------------------+
| **Recitation**         | TBD           |                                                                    |
+------------------------+---------------+--------------------------------------------------------------------+

: {.hover}

### Week 9

+-------------------------+------------------+------------------------------------------------------------------------------+
| **Monday, March 9**     | Water and Health | -   [**Read:**]{.underline} Frumkin, Chapter 16 + **clicker quiz**           |
|                         |                  |     -   Print: pp. 413-422                                                   |
|                         |                  |     -   PDF: pp. 421-449                                                     |
+-------------------------+------------------+------------------------------------------------------------------------------+
| **Wednesday, March 11** | Water and Health |                                                                              |
+-------------------------+------------------+------------------------------------------------------------------------------+
| **Recitation**          | TBD              | -   [**Due Friday March 13 \@ 5:00 pm**]{.underline}**:** Discourse Analysis |
+-------------------------+------------------+------------------------------------------------------------------------------+

: {.hover}

### Week 10

+-------------------------+--------------+----------+
| **Monday, March 16**    | SPRING BREAK | -   None |
+-------------------------+--------------+----------+
| **Wednesday, March 18** | SPRING BREAK | -   None |
+-------------------------+--------------+----------+
| **Recitation**          | SPRING BREAK | -   None |
+-------------------------+--------------+----------+

: {.hover}

## Part 3: Environmental Health Policy & Practice

### Week 11

+-------------------------+-----------------------------+---------------------------------------------------------------------------------+
| **Monday, March 23**    | Environmental Health Policy | -   [**Read:**]{.underline} Frumkin, Chapter 26 + **clicker quiz**              |
|                         |                             |     -   Print: pp. 725-740                                                      |
|                         |                             |     -   PDF: pp. 717-729                                                        |
+-------------------------+-----------------------------+---------------------------------------------------------------------------------+
| **Wednesday, March 25** |                             |                                                                                 |
+-------------------------+-----------------------------+---------------------------------------------------------------------------------+
| **Recitation**          |                             | -   [**Due Friday March 27 \@ 5:00 pm**]{.underline}**:** Group policy proposal |
+-------------------------+-----------------------------+---------------------------------------------------------------------------------+

: {.hover}

### Week 12

+------------------------+--------------------+------------------------------------------------------------------------------------------------+
| **Monday, March 30**   | Climate and Health | -   [**Read:**]{.underline} Frumkin, Chapter 12 + **clicker quiz**                             |
|                        |                    |     -   Print: pp. 275-304                                                                     |
|                        |                    |     -   PDF: pp. 290-316                                                                       |
+------------------------+--------------------+------------------------------------------------------------------------------------------------+
| **Wednesday, April 1** |                    |                                                                                                |
+------------------------+--------------------+------------------------------------------------------------------------------------------------+
| **Recitation**         |                    | -   [**Due Friday April 3 \@ 5:00 pm**]{.underline}**:** Policy analysis Intro & Methods draft |
+------------------------+--------------------+------------------------------------------------------------------------------------------------+

: {.hover}

### Week 13

+------------------------+---------------+------------------------------------------------------------------------------------------------------+
| **Monday, April 6**    | Energy Policy | -   [**Read:**]{.underline} Frumkin, Chapter 14 + **clicker quiz**                                   |
|                        |               |     -   Print: pp. 345-365                                                                           |
|                        |               |     -   PDF: 355-373                                                                                 |
+------------------------+---------------+------------------------------------------------------------------------------------------------------+
| **Wednesday, April 8** |               |                                                                                                      |
+------------------------+---------------+------------------------------------------------------------------------------------------------------+
| **Recitation**         |               | -   [**Due Friday April 10 \@ 5:00 pm**]{.underline}**:** Policy analysis Results & Discussion draft |
+------------------------+---------------+------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 14

+-------------------------+----------------+--------------------------------------------------------------------+
| **Monday, April 13**    | Urban Planning | -   [**Read:**]{.underline} Frumkin, Chapter 15 + **clicker quiz** |
|                         |                |     -   Print: pp. 377-400                                         |
|                         |                |     -   PDF: pp. 388-409                                           |
+-------------------------+----------------+--------------------------------------------------------------------+
| **Wednesday, April 15** |                |                                                                    |
+-------------------------+----------------+--------------------------------------------------------------------+
| **Recitation**          |                |                                                                    |
+-------------------------+----------------+--------------------------------------------------------------------+

: {.hover}

### Week 15

+-------------------------+-----------------+---------------------------------------------------------------------------------+
| **Monday, April 20**    | Risk Assessment | -   [**Read:**]{.underline} Frumkin, Chapter 27 + **clicker quiz**              |
|                         |                 |     -   Print: pp. 747-764                                                      |
|                         |                 |     -   PDF: pp. 736-751                                                        |
+-------------------------+-----------------+---------------------------------------------------------------------------------+
| **Wednesday, April 22** |                 |                                                                                 |
+-------------------------+-----------------+---------------------------------------------------------------------------------+
| **Recitation**          |                 | -   [**Due Friday April 24 \@ 5:00 pm**]{.underline}**:** Final policy analysis |
+-------------------------+-----------------+---------------------------------------------------------------------------------+

: {.hover}

### Week 16

+------------------------+-------------------+--------------------------------------------------------------------------+
| **Friday, May 1**      | Final Exam Period | -   [**Due**]{.underline}**:** Group policy analysis poster presentation |
|                        |                   |                                                                          |
| 10:30 a.m. - 1:00 p.m. |                   |                                                                          |
+------------------------+-------------------+--------------------------------------------------------------------------+

: {.hover}
