---
title: "Syllabus"
subtitle: "ENVS 3030 | Environmental Health | Spring 2026"
---

> **en·​vi·​ron·​ment:**
>
> *the circumstances, objects, or conditions by which one is surrounded: the factors and influences that affect the growth, health, progress, functioning, etc., of someone or something*
>
> \~Oxford English Dictionary

### Course Description

How does the “environment” influence human health? This course will explore the many ways that our surroundings—both the natural and built environments—positively and negatively shape the health of human communities. Through the lens of diverse topics within the field of environmental health—including ecology and ecosystem services, sustainability and climate change, toxicology, exposure and risk assessment, environmental justice, air and water pollution, energy policy, and more—students will develop practical social science research skills to frame environmental health problems, collect and analyze data to answer research questions, evaluate current environmental health policies, and think critically about how their own environment influences their health. This course is appropriate for all students interested in understanding the complex interactions between our environment and public health and in growing as critical thinkers and social scientists.

### Instructors

**Professor:** Riley Mulhern \| [riley.mulhern\@colorado.edu](mailto:riley.mulhern@colorado.edu) \| SEEC S237A

**Teaching Assistant:** Lambert Lin \| [lambert.lin\@colorado.edu](mailto:lambert.lin@colorado.edu)

### Lecture

-   **Meeting time:** M/W 10:40 – 11:30 a.m.

-   **Location:** SEEC N136

### Recitations

You should be enrolled in one of these:

|             |                          |              |
|-------------|--------------------------|--------------|
| **Section** | **Time**                 | **Location** |
| Section 011 | Th 8:30 – 9:20 a.m.      | SEEC N126    |
| Section 012 | Th 4:05 – 4:55 p.m.      | SEEC S125    |
| Section 013 | F 10:40 – 11:30 a.m**.** | SEEC N129    |

### Required Text

[Frumkin, H. (Ed.), 2016. Environmental Health: From Global to Local, 3^rd^ edition. Jossey-Bass, San Francisco.](https://www.wiley.com/en-us/Environmental+Health%3A+From+Global+to+Local%2C+3rd+Edition-p-9781118984765)

### Learning Objectives

By the end of this course, you should be able to:

1.  Describe the ways in which the natural and built environments influence the health of human communities.

2.  Reflect personally on the positive and negative influences of environmental conditions on health to connect classroom learning to lived experience.

3.  Employ multiple social science research methods to critically evaluate a range of environmental health topics.

4.  Interpret, analyze, and discuss contrasting perspectives around current environmental health policies using scientific data and evidence.

5.  Collect and analyze research data and effectively communicate findings in written assignments, verbal presentations, and visual graphics.

### Assignments

#### Readings

You will be expected to read approximately one chapter of the assigned textbook each week plus additional methods-focused readings and come to class prepared for weekly quizzes and discussion of the material. The assigned readings will provide essential baseline knowledge and “scaffolding” for the assignments in this class. Earnestly engaging in the reading material will be an important predictor of your success in this class.

#### Recitation reflections

To enhance your learning, you will respond to a writing prompt to reflect on the week’s reading at the beginning of each recitation session. You can use your notes and the text for these exercises, but they must be handwritten. The TA will collect your reflections randomly during the semester to grade your responses for completeness and thoughtful engagement of the material.

#### Weekly clicker quizzes

There will not be any mid-term or final exams in this class. Instead, we will have weekly in-class clicker quizzes based on the assigned readings. These will be graded for correctness and will make up 30% of your overall grade. Think of it as a mid-term exam spread out into small chunks over the whole semester.

#### Assignment #1: Discourse Analysis \[Individual\]

You will conduct a **discourse analysis** on a press release of your choosing from the Environmental Protection Agency (EPA) Newsroom. You can choose any topic (and time period/administration) anything that strikes your interest that is relevant to this class. How are language, framing, and storytelling used to influence the policy narrative? You will submit a 1-2 page policy discourse analysis. Further details will be provided on Canvas.

-   **EPA Newsroom:** <https://www.epa.gov/newsroom/browse-news-releases>

-   **Research methods developed**: Discourse analysis

-   **Due date:** TBD

#### Assignment #2: Environmental Health Diary Study \[Individual + Group\]

You will participate in a class-wide **diary study** of environmental health conditions and behaviors and analyze the results. Diary studies are a qualitative research method used by ethnographers to understand human experience and behaviors. With digital tools, it is now commonly used by businesses and software companies to understand user experiences (UX) with products or software systems. In this class, we will use this same method to understand our collective experiences with our environments to evaluate potential patterns and health risks. In the process, you will also gain hands on experience with a practical (and marketable) UX research method. Further instructions will be provided on Canvas.

-   **Research methods developed**: Behavior tracking / diary study  

-   **Due date:** TBD

#### Assignment #3: Environmental Health Policy Analysis \[Group\]

Working in groups of 3-4, you will research an environmental health decision, regulation, or policy of your choice. This can be related to anything that we cover in the class (for example air or water quality, solid waste, energy production, access to green space, etc.). As a group, you will first submit a project proposal for which policy you plan to study. You will then use established methods of **stakeholder mapping** and **process tracing** to analyze the effectiveness of the policy/intervention and how/why it worked or not, culminating in a final report and poster presentation for the class.

-   **Research methods developed**: Stakeholder mapping, process tracing

-   **Due dates:**

    -   Policy proposal: Wednesday January 28

    -   Introduction and Methods draft: Wednesday February 25

    -   Results & Discussion draft: Monday March 30

    -   Final report: Wednesday April 22

    -   Poster presentation: Friday May 1 \[Final exam period\]

### Evaluation & Grading

You will be evaluated according to the table below. Each assignment has a designated point value so you can always know how you are doing in the class. Note that your participation in class and the recitations—including coming prepared having done the readings, completing the reflections, and weekly quizzes—is worth a significant proportion of your grade! Doing well in this class requires meaningful effort on your part in both class time and assignments.  

+----------------------------------------------------------------------------------------------+----------------------+------------------+
|                                                                                              | Points awarded       | Percent of grade |
+==============================================================================================+======================+==================+
| ##### **Informed Participation**                                                             | ##### **35 points**  | ##### **25%**    |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Class attendance and active engagement (1 point per class session, 3 free absences)          | 24 points            | 12%              |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Recitation attendance and active engagement (1 point per recitation session, 1 free absence) | 14 points            | 7%               |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Recitation reflections                                                                       | 12 points            | 6%               |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| ##### **Weekly Quizzes (15 quizzes, 4 points each)**                                         | ##### **60 points**  | ##### **30%**    |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| ##### **Assignment 1: EPA Newsroom Discourse Analysis**                                      | ##### **20 points**  | ##### **10%**    |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| ##### **Assignment 2: Environmental Health Diary Study**                                     | ##### **30 points**  | ##### **15%**    |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Diary entries/participation                                                                  | 10 points            | 5%               |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Individual analysis/reflection                                                               | 10 points            | 5%               |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Group summary and analysis                                                                   | 10 points            | 5%               |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| ##### **Assignment 3: Environmental Health Policy Analysis**                                 | ##### **30 points**  | ##### **15%**    |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Policy Proposal                                                                              | 5 points             | 2.5%             |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Introduction and Methods draft                                                               | 5 points             | 2.5%             |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Results & Discussion draft                                                                   | 5 points             | 2.5%             |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Final report                                                                                 | 5 points             | 2.5%             |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| Poster presentation                                                                          | 10 points            | 5%               |
+----------------------------------------------------------------------------------------------+----------------------+------------------+
| ##### **TOTAL:**                                                                             | ##### **200 points** | ##### **100%**   |
+----------------------------------------------------------------------------------------------+----------------------+------------------+

The number of points you earn will be converted to a letter grade as follows:

| Point Total | Course Grade |
|:-----------:|:------------:|
|   186-200   |      A       |
|   180-185   |      A-      |
|   174-179   |      B+      |
|   166-173   |      B       |
|   160-165   |      B-      |
|   154-159   |      C+      |
|   146-153   |      C       |
|   140-145   |      C-      |
|   134-139   |      D+      |
|   126-133   |      D       |
|   120-125   |      D-      |
|    0-119    |      F       |

### Course Policies & Expectations

#### Attendance

Attendance is included in your course participation grade. Please come on time and prepared. You are allowed [**three**]{.underline} absences for any reason over the course of the semester – no questions asked. Please do not email me regarding your three absences. If you need to miss additional class time beyond your three allowed absences for health-related reasons or religious observations, please let me know via email before class when possible.

#### Late Work

One point will be subtracted for late submissions, with another one point subtracted for every 24 hours after the deadline. Assignments that are more than 5 days late will not be accepted. We are willing to work with you if you have a reason that makes it difficult for you to meet a deadline due to medical or religious accommodation. In these cases, please contact the professor or TA in advance to discuss your situation.

#### Email Policy

The best way to receive help in this course is to set up an appointment during my office hours. If you have specific problems or questions that cannot be addressed during office hours, an urgent matter, or need a medical or religious accommodation, please email me with “ENVS 3030” and a brief keyword or two in the subject line. I will do my best to respond promptly to student emails but please be patient. Feel free to remind me if I have not gotten back to you within 72 hours. Please also check your CU email regularly to stay up to date with all course announcements following [CU’s student email policy](https://www.colorado.edu/compliance/policies/student-e-mail-policy).

#### Devices in Class

We all struggle these days with the ways in which our devices distract us. Research shows that [distractions can significantly decrease IQ](https://www.scientificamerican.com/article/distractions-lower-our-iq/) and lead to worse academic performance. If you are in class while multitasking or checking social media, you are not actually *learning* anything at all. The technology policy in class is thus designed to support your attention to each other and the course material. Cell phones and laptops should be kept out of sight unless as directed for specific activities. If you have an academic accommodation or other specific reason that would require a device during class, I am happy to make exceptions. Please just come talk to me ahead of time. **You are strongly encouraged to keep a physical pen-and-paper notebook**. Pen and paper can’t distract you like a computer can and writing by hand has been shown to have [cognitive benefits](https://doi.org/10.17239/jowr-2015.07.02.1) that aid with memory and recall.

#### Plagiarism

All assignments for this course must be your original work. While I encourage you to talk about ideas and course materials with your classmates, all assignments must be your own. CU’s plagiarism software will automatically review online submissions to Canvas. If I determine that you have intentionally copied material from any source as if it were your own—including websites, periodicals, journals, publications, other students’ past work, **and/or AI-generated content**—you will be reported for academic dishonesty. Please see me and/or consult the resources below if you have questions about proper citation of your work to avoid plagiarism. I am happy to help with this!

-   [Harvard style guide](https://www5.open.ac.uk/library/referencing-and-plagiarism/quick-guide-to-harvard-referencing-cite-them-right) (this is a common citation style in academic environmental science journals and the citation style you will use for the capstone project)

-   [Best Practices to Avoid Plagiarism](https://owl.purdue.edu/owl/avoiding_plagiarism/best_practices.html)

-   [CU Writing Center](https://www.colorado.edu/program/writingcenter)

#### AI Policy

::: callout-important
As noted above, turning in AI-generated content as if it were your own work will be considered plagiarism. It is a waste of your efforts, your intentions, and your money to circumvent the hard work of thinking/writing for yourself. **As such, you are responsible for resisting the use of AI tools for your original writing**. At the same time, I recognize the power of AI and LLM technology as a research and learning aid. You are allowed to use AI tools such as Microsoft Copilot, Google Gemini, Chat GPT, Claude or others in the same way that you use search engines to understand scientific concepts, find new resources, or explore new topics. However, **the content generated by these tools cannot be cited**; they should always lead you to a primary source.

-   ***Exception for ENVS 3030:*** For Assignment #2 in this class, we will use AI to help analyze data generated by the class. We will discuss appropriate use of these tools for this assignment in class.
:::

### University Policies

In addition to the above course-specific expectations, you should be familiar with the following standard university policies.

#### Classroom Behavior

Students and faculty are responsible for maintaining an appropriate learning environment in all instructional settings, whether in person, remote, or online. Failure to adhere to such behavioral standards may be subject to discipline. Professional courtesy and sensitivity are especially important with respect to individuals and topics dealing with race, color, national origin, sex, pregnancy, age, disability, creed, religion, sexual orientation, gender identity, gender expression, veteran status, marital status, political affiliation, or political philosophy. For more information, see the [classroom behavior policy](http://www.colorado.edu/policies/student-classroom-and-course-related-behavior), the[ ](https://www.colorado.edu/sccr/student-conduct)[Student Code of Conduct](https://www.colorado.edu/sccr/media/230), and the[Office of Institutional Equity and Compliance](https://www.colorado.edu/oiec/).

#### Accommodation for Disabilities, Temporary Medical Conditions, and Medical Isolation.

If you qualify for accommodations because of a disability, please submit your accommodation letter from Disability Services to your faculty member in a timely manner so that your needs can be addressed.  Disability Services determines accommodations based on documented disabilities in the academic environment.  Information on requesting accommodations is located on the [Disability Services website](https://www.colorado.edu/disabilityservices/). Contact Disability Services at 303-492-8671 or [DSinfo\@colorado.edu](mailto:DSinfo@colorado.edu)  for further assistance.  If you have a temporary medical condition, see [Temporary Medical Conditions](https://www.colorado.edu/disabilityservices/students/temporary-medical-conditions) on the Disability Services website. If you have a temporary illness, injury or required medical isolation for which you require adjustment, please let me know via email and I will be happy to make an accommodation.

#### Prefered Names & Pronouns

CU Boulder recognizes that students' legal information doesn't always align with how they identify. Students may update their preferred names and pronouns via the student portal; those preferred names and pronouns are listed on instructors' class rosters. In the absence of such updates, the name that appears on the class roster is the student's legal name.

#### Honor Code

All students enrolled in a University of Colorado Boulder course are responsible for knowing and adhering to the[ ](https://www.colorado.edu/sccr/honor-code)[Honor Code](https://www.colorado.edu/sccr/media/229). Violations of the Honor Code may include but are not limited to: plagiarism (including use of paper writing services or technology \[such as essay bots\]), cheating, fabrication, lying, bribery, threat, unauthorized access to academic materials, clicker fraud, submitting the same or similar work in more than one course without permission from all course instructors involved, and aiding academic dishonesty. Understanding the course's syllabus is a vital part in adhering to the Honor Code. All incidents of academic misconduct will be reported to Student Conduct & Conflict Resolution: [StudentConduct\@colorado.edu](mailto:StudentConduct@colorado.edu). Students found responsible for violating the[ ](https://www.colorado.edu/sccr/honor-code)[Honor Code](https://www.colorado.edu/sccr/media/229) will be assigned resolution outcomes from the Student Conduct & Conflict Resolution as well as be subject to academic sanctions from the faculty member. Visit [Honor Code](https://www.colorado.edu/sccr/media/229) for more information on the academic integrity policy.

#### Sexual Misconduct, Discrimination, Harassment and/or Related Retaliation

CU Boulder is committed to fostering an inclusive and welcoming learning, working, and living environment. University policy prohibits [protected-class](https://www.colorado.edu/oiec/policies/discrimination-harassment-policy/protected-class-definitions) discrimination and harassment, sexual misconduct (harassment, exploitation, and assault), intimate partner abuse (dating or domestic violence), stalking, and related retaliation by or against members of our community on- and off-campus. The Office of Institutional Equity and Compliance (OIEC) addresses these concerns, and individuals who have been subjected to misconduct can contact OIEC at 303-492-2127 or email [CUreport\@colorado.edu](mailto:CUreport@colorado.edu). Information about university policies, [reporting options](https://www.colorado.edu/oiec/reporting-resolutions/making-report), and [support resources](https://www.colorado.edu/oiec/support-resources) including confidential services can be found on the [OIEC website](http://www.colorado.edu/institutionalequity/).

Please know that faculty and graduate instructors must inform OIEC when they are made aware of incidents related to these policies regardless of when or where something occurred. This is to ensure that individuals impacted receive outreach from OIEC about resolution options and support resources. To learn more about reporting and support for a variety of concerns, visit the [Don’t Ignore It](https://www.colorado.edu/dontignoreit/) [page]{.underline}.

#### Religious Accommodations

Campus policy requires faculty to provide reasonable accommodations for students who, because of religious obligations, have conflicts with scheduled exams, assignments or required attendance. Please communicate the need for a religious accommodation with me via email in a timely manner. See the [campus policy regarding religious observances](http://www.colorado.edu/policies/observance-religious-holidays-and-absences-classes-andor-exams) for full details.

#### Mental Health and Wellness

The University of Colorado Boulder is committed to the well-being of all students. If you are struggling with personal stressors, mental health or substance use concerns that are impacting academic or daily life, please contact [Counseling and Psychiatric Services (CAPS)](https://www.colorado.edu/counseling/ "https://www.colorado.edu/counseling/") located in C4C or call (303) 492-2277, 24/7. Free and unlimited telehealth is also available through [Academic Live Care](https://www.colorado.edu/health/academiclivecare "https://www.colorado.edu/health/academiclivecare"). The [Academic Live Care](https://www.colorado.edu/health/academiclivecare "https://www.colorado.edu/health/academiclivecare") site also provides information about additional wellness services on campus that are available to students.
