---
title: "Course Description"
---

> **en·​vi·​ron·​ment:**
>
> *the circumstances, objects, or conditions by which one is surrounded: the factors and influences that affect the growth, health, progress, functioning, etc., of someone or something*
>
> \~Oxford English Dictionary

How does the “environment” influence human health? This course will explore the many ways that our surroundings—both the natural and built environments—positively and negatively shape the health of human communities. Through the lens of diverse topics within the field of environmental health—including ecology and ecosystem services, sustainability and climate change, toxicology, exposure and risk assessment, environmental justice, air and water pollution, energy policy, and more—students will develop practical social science research skills to frame environmental health problems, collect and analyze data to answer research questions, evaluate current environmental health policies, and think critically about how their own environment influences their health. This course is appropriate for all students interested in understanding the complex interactions between our environment and public health and in growing as critical thinkers and social scientists.
