---
title: "Schedule"
subtitle: "ENVS 4800 | Water Quality & Health Risks | Spring 2026"
format: 
  html:
    toc-expand: true
tbl-colwidths: [20,20,60]
---

## Introduction

### Week 1

+---------------------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**                  | **Topic**                      | **Readings & Assignments**                                                                                                                                                          |
+---------------------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, January 12**    | Course Intro                   | -   [**Read**]{.underline}***:*** Cloud, John. 2009. “Study: Doodling Helps You Pay Attention.” <https://time.com/archive/6933247/study-doodling-helps-you-pay-attention/>          |
|                           |                                | -   [**Read**]{.underline}***:*** Morris, Giles. 2009. “If you only do one thing this week, avoid multitasking.” <https://www.theguardian.com/money/2009/oct/05/avoid-multitasking> |
+---------------------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, January 14** | Intro to Water Safety Planning | -   [**Read**]{.underline}:                                                                                                                                                         |
|                           |                                |                                                                                                                                                                                     |
|                           |                                |     -   WHO. “Water safety planning: an overview and guide to success.” In: *Water safety plan manual*. 2023. **pp. 8-12**                                                          |
|                           |                                |                                                                                                                                                                                     |
|                           |                                |     -   WHO. "Introduction.” In: *A Guide to Equitable Water Safety Planning*. 2019. **pp. 1-7.**                                                                                   |
+---------------------------+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

## Part 1: Understanding Drinking Water Systems

### Week 2

+---------------------------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, January 19**    | No class - Martin Luther King Jr. day             | -   None                                                                                                                                                                    |
+---------------------------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, January 21** | John Snow and the Origins of Sanitary Engineering | -   [**Watch**]{.underline}**:**                                                                                                                                            |
|                           |                                                   |                                                                                                                                                                             |
|                           |                                                   |     -   “The 1850s map that changed how we fight outbreaks.” <https://www.youtube.com/watch?v=VJ86D_DtyWg>                                                                  |
|                           |                                                   |                                                                                                                                                                             |
|                           |                                                   |     -   “John Snow and the 1854 Broad Street cholera outbreak.” <https://www.youtube.com/watch?v=lNjrAXGRda4>                                                               |
|                           |                                                   |                                                                                                                                                                             |
|                           |                                                   | -   [**Read:**]{.underline} Snow, John. “Dr. Snow’s Report.” 1855. In: *Report on the Cholera Outbreak in the Parish of St. James, Westminster, during the Autumn of 1854.* |
+---------------------------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 3

+---------------------------+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, January 26**    | Water and Public Health                  | -   [**Read**]{.underline}**:** Cutler and Miller. “The Role of Public Health Improvements in Health Advances: The Twentieth-Century United States.” 2005. *Demography.* |
+---------------------------+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, January 28** | Equity & Representation in Water Systems | -   [**Read**]{.underline}:                                                                                                                                              |
|                           |                                          |                                                                                                                                                                          |
|                           |                                          |     -   WHO. “Module 1: Assembling the WSP team.” In: *Water safety plan manual*. 2023. **pp. 20-28**                                                                    |
|                           |                                          |                                                                                                                                                                          |
|                           |                                          |     -   WHO. "Assembling the WSP Team.” In: *A Guide to Equitable Water Safety Planning*. **pp. 8-11.**                                                                  |
+---------------------------+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 4

+---------------------------+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, February 2**    | Waterborne Disease Outbreaks        | -   [**Read**]{.underline}**:**                                                                                                                                                                                    |
|                           |                                     |                                                                                                                                                                                                                    |
|                           |                                     |     -   **Last name starts with A – G:** Piarroux et al. “Understanding the cholera epidemic, Haiti.” 2011. *Emerging Infectious Diseases.*                                                                        |
|                           |                                     |                                                                                                                                                                                                                    |
|                           |                                     |     -   **Last name starts with H – Z:** MacKenzie et al. “A Massive Outbreak in Milwaukee of Cryptosporidium Infection Transmitted Through the Public Water Supply.” 1994. *The New England Journal of Medicine.* |
+---------------------------+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, February 4** | U.S. Water & Wastewater Regulations | -   [**Due:**]{.underline} WSP Module 1 Draft                                                                                                                                                                      |
+---------------------------+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 5

+----------------------------+-------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, February 9**     | **Field Trip**                      | -   [**Read**]{.underline}**:**                                                                                                                                                                                                              |
|                            |                                     |                                                                                                                                                                                                                                              |
|                            | Drinking Water Treatment Plant Tour |     -   WHO. “Module 2: Describing the system.” In: *Water safety plan manual*. 2023. **pp. 29-38**                                                                                                                                          |
|                            |                                     |                                                                                                                                                                                                                                              |
|                            |                                     |     -   WHO. "Describing the System.” In: *A Guide to Equitable Water Safety Planning*. 2019. **pp. 12-17.**                                                                                                                                 |
+----------------------------+-------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, February 11** | Benefits of Water Safety Planning   | -   [**Read**]{.underline}**:** Baum et al. “An examination of the potential added value of water safety plans to the United States national drinking water legislation.” 2015. *International Journal of Hygiene and Environmental Health.* |
+----------------------------+-------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

## Part 2: Understanding Drinking Water Risks

### Week 6

+----------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, February 16**    | Water Safety Plan Workday - Hazards & Risks | -   [**Read:**]{.underline}                                                                                                                        |
|                            |                                             |                                                                                                                                                    |
|                            |                                             |     -   WHO. “Module 3: Identifying hazards and hazardous events.” In: *Water safety plan manual*. 2023. **pp. 39-46**                             |
|                            |                                             |                                                                                                                                                    |
|                            |                                             |     -   WHO. “Module 4: Validating existing control measures and assessing risks.” In: *Water safety plan manual*. 2023. **pp. 47-58 and 132-133** |
|                            |                                             |                                                                                                                                                    |
|                            |                                             |     -   WHO. "Identifying Hazardous Events.” In: *A Guide to Equitable Water Safety Planning*. 2019. **pp. 17-18.**                                |
+----------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, February 18** | Emerging Contaminants (UCMR & CCL)          | -   [**Read:**]{.underline} Siegel. “Chapter 3: An Endless Road to Nowhere." 2019. In: *Troubled Water.*                                           |
|                            |                                             |                                                                                                                                                    |
|                            |                                             | -   [**Due:**]{.underline} WSP Module 2 Draft                                                                                                      |
+----------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 7

+----------------------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, February 23**    | Carcinogens | -   [**Read:**]{.underline} Steingraber. “Chapter 9: water.” 2010. In: *Living Downstream*.                                                                                                                                                      |
+----------------------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, February 25** | Lead        | -   [**Read**]{.underline}**:** Hanna-Attisha et al. “Elevated Blood Lead Levels in Children Associated With the Flint Drinking Water Crisis: A Spatial Analysis of Risk and Public Health Response.” 2016. *American Journal of Public Health.* |
+----------------------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 8

+------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, March 2**    | Lead    | -   1st half of class to bring water samples for analysis                                                                                                                                                |
|                        |         |                                                                                                                                                                                                          |
|                        |         | -   [**1st half of class read**]{.underline}**:** Adhikara et al. “Influence of point-of-use dispensers on lead level assessment in drinking water of a lead pipe-free campus.” 2022. *npj Clean Water*. |
|                        |         |                                                                                                                                                                                                          |
|                        |         | -   In-class activity - Develop Part 1 of EHS results report                                                                                                                                             |
+------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, March 4** | Lead    | -   2nd half of class to bring water samples for analysis                                                                                                                                                |
|                        |         |                                                                                                                                                                                                          |
|                        |         | -   [**2nd half of class read**]{.underline}**:** Adhikara et al. “Influence of point-of-use dispensers on lead level assessment in drinking water of a lead pipe-free campus.” 2022. *npj Clean Water*. |
|                        |         |                                                                                                                                                                                                          |
|                        |         | -   In-class activity - Develop Part 2 of EHS results report                                                                                                                                             |
+------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 9

+-------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+
| **Monday, March 9**     | Microplastics                                                                               | -   [**Read**]{.underline}**:** TBD  |
+-------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+
| **Wednesday, March 11** | PFAS                                                                                        | -   [**Due**]{.underline}: Blog post |
|                         |                                                                                             |                                      |
|                         | **Guest lecture:** Dr. Kelsey Schreiber, Colorado Department of Public Health & Environment |                                      |
+-------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+

: {.hover}

### Week 10

+--------------------------+---------------------+-----------------+
| **Monday, March 16**     | SPRING BREAK        | -   None        |
+--------------------------+---------------------+-----------------+
| **Wednesday, March 18**  | SPRING BREAK        | -   None        |
+--------------------------+---------------------+-----------------+

: {.hover}

### Week 11

+-------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, March 23**    | Wastewater Impacts on Drinking Water | -   [**Read**]{.underline}**:** Focazio et al. “A national reconnaissance for pharmaceuticals and other organic wastewater contaminants in the United States — II) Untreated drinking water sources.” 2008. *Science of the Total Environment.* |
+-------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, March 25** | **Field Trip**                       |                                                                                                                                                                                                                                                 |
|                         |                                      |                                                                                                                                                                                                                                                 |
|                         | Wastewater Treatment Plant Tour      |                                                                                                                                                                                                                                                 |
+-------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 12

+------------------------+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Monday, March 30**   | Arsenic OR HABs (TBD) | -   [**Read:**]{.underline} TBD                                                                                                                             |
+------------------------+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, April 1** | Fluoride              | -   [**Read**]{.underline}**:** Taylor et al. “Fluoride Exposure and Children’s IQ Scores: A Systematic Review and Meta-Analysis.” 2025. *JAMA Pediatrics.* |
|                        |                       |                                                                                                                                                             |
|                        |                       | -   [**Due:**]{.underline} WSP Module 3/4 draft                                                                                                             |
+------------------------+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {.hover}

## Part 3. Improving Water Quality

### Week 13

+------------------------+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
| **Monday, April 6**    | Water Safety Plan Workday - Improvements | -   [**Read**]{.underline}**:**                                                                                          |
|                        |                                          |                                                                                                                          |
|                        |                                          |     -   WHO. “Module 5: Planning for improvement.” In: *Water safety plan manual*. 2023. **pp. 59-66**                   |
|                        |                                          |                                                                                                                          |
|                        |                                          |     -   WHO. "Improvement Planning.” In: *A Guide to Equitable Water Safety Planning*. 2019. **pp. 19-23.**              |
+------------------------+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
| **Wednesday, April 8** | Technology, Innovation, & Investment     | -   [**Read**]{.underline}**:**                                                                                          |
|                        |                                          |                                                                                                                          |
|                        |                                          |     -   Sedlak. “How Development of America’s Water Infrastructure Has Lurched Through History.” 2019. *Trend Magazine.* |
|                        |                                          |                                                                                                                          |
|                        |                                          |     -   Water reuse (TBD)                                                                                                |
+------------------------+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+

: {.hover}

### Week 14

+-------------------------+-----------------+-----------------------------------------------+
| **Monday, April 13**    | POU/POE Systems | -   [**Read:**]{.underline} TBD               |
+-------------------------+-----------------+-----------------------------------------------+
| **Wednesday, April 15** | Pick a Question | -   [**Due:**]{.underline} WSP Module 5 draft |
+-------------------------+-----------------+-----------------------------------------------+

: {.hover}

### Week 15

+-------------------------+------------------------------+---------------------------------------------------------------+
| **Monday, April 20**    | Lightning Talk Presentations | -   [**Due:**]{.underline} Lightning Talk presentation slides |
+-------------------------+------------------------------+---------------------------------------------------------------+
| **Wednesday, April 22** | Lighting Talk Presentations  |                                                               |
+-------------------------+------------------------------+---------------------------------------------------------------+

: {.hover}

### Week 16

+-------------------------+------------------------------+-------------------------------------------------------------------+
| **Wednesday, April 29** | Final Exam Period            | -   [**Due:**]{.underline} Final written Water Safety Plan report |
|                         |                              |                                                                   |
| 4:30 - 7:00 p.m.        | Lightning Talk Presentations |                                                                   |
+-------------------------+------------------------------+-------------------------------------------------------------------+

: {.hover}
