---
title: "Syllabus"
subtitle: "ENVS 4800 | Water Quality & Health Risks | Spring 2026"
toc: true
---

> “*Our water resources, more perhaps than any other, illustrate the interaction of all parts of the environment... Everything that man himself injects into the biosphere - chemical, biological or physical - can ultimately find its way into the earth's water*.”
>
> \~[Charles C. Johnson, Jr.](https://dcp.psc.gov/OSG/engineer/history-cjohnson.aspx), Assistant Surgeon General of the United States, 1972

### Course Description

Nowhere is the relationship between humans and the environment more evident than in the water we drink. Water is a fundamental good provided by nature; our bodies are made of nearly 60% water and our societies are largely arranged around sourcing, storing, and distributing it. And yet, the core functions of society—production of food, extraction of raw materials, manufacturing of products, generation of energy, construction of roads, etc.—generate waste that pollutes natural water bodies and threatens public health. Water quality is, thus, simultaneously a reflection of our impact on the environment and the environment’s impact on us.

This course will explore this cycle of human impacts and dependence on water by examining the science behind different contaminants in drinking water supplies and their potential health risks. We will study where contaminants come from, how they get into our water supplies, what kind of risk they represent, and what can be done about them. We will consider how engineered barriers mediate the relationship between environmental pollution and human health, and how/when such barriers fall short.  We will ask: where does our water come from? What potential hazards and sources of contamination are there along its path from source to tap? How is drinking water deemed "safe"? This course will help students develop a critical understanding of drinking water quality, provide hands-on training around collecting and analyzing water quality data, and equip students to make evidence-based recommendations to communities and stakeholders to reduce drinking water exposures and protect public health.

### Instructors

**Professor:** Riley Mulhern \| [riley.mulhern\@colorado.edu](mailto:riley.mulhern@colorado.edu) \| SEEC S237A

### Lecture

-   **Meeting time:** M/W 4:05 – 5:20 p.m.

-   **Location:** SEEC N136

### Required Text

There is no required textbook for this course. All readings will be provided digitally as PDFs.

### Learning Objectives

By the end of this course, you should be able to:

1.  Critically evaluate quantitative and qualitative evidence to formulate technical recommendations around water quality risks.

2.  Independently seek out, compile, and analyze data and information to produce a professional-quality Water Safety Plan aimed toward environmental, industry, and public health stakeholders in your community.

3.  Effectively communicate scientific information about water quality and health to both popular and academic audiences in written and verbal formats.

4.  Articulate how disparities in drinking water quality represent an environmental justice concern.

### Assignments

#### Find my office!

The easiest assignment of your life will be to simply [set up an appointment](https://zcal.co/i/XOmiXVRD) and come introduce yourself (in person!) within the first three weeks of the semester. The assignments in this class will be open ended and will require you to ask for help when you get stuck, so I want you to be familiar with where to find me and how to set up an appointment. You can also come visit in pairs or small groups. Just come say hello.

#### Readings

There is an enormous amount of “noise” about water quality and health risks today. Water quality concerns frequently make the headlines, but news sources and social media often sensationalize the issues for the public without a thorough understanding of the science. In contrast, the readings in this course will mostly consist of peer-reviewed, scientific journal articles or other primary sources. Learning to read, interpret, and synthesize primary scientific research is itself an essential skill for environmental professionals today to cut through the noise and be trusted “translators” of technical scientific information. Thus, you will be expected to read and come to class prepared to discuss one full-length journal article or other scholarly work assigned each week.

#### In-Class Writing Assignments

To enhance your learning, weekly in-class writing assignments will be given about each reading. These will consist of a few questions about the study and/or connections to other readings, as appropriate. These will provide the basis for in-class discussions and make up a large proportion of your participation grade. I will collect your reflections randomly during the semester and grade them for the quality of the reflections. These writing assignments will be “closed book,” so you will not be allowed to have the text in front of you or your laptop open, but you may use any notes you take on the reading. If you have made a good-faith effort to read and understand the week’s text, these should not be difficult. Think of them more as an opportunity to reflect on each week’s reading.

#### Campus Lead Testing Project \[In class\]

As part of a module on lead in drinking water in this course, we will be working with CU Environmental Health and Safety (EHS) and Facilities Management to screen taps on campus for potential lead concerns. The class will work together to “crowdsource” water samples, analyze the results in class, and communicate the results with  EHS and Facilities Management.

#### Emerging Contaminant Blog Post

In the spirit of learning to be effective science communicators, you will research an emerging water quality contaminant of health concern (either chemical or microbial) from the U.S. Environmental Protection Agency’s [Contaminant Candidate List 5](https://www.epa.gov/ccl/contaminant-candidate-list-5-ccl-5) and write a concise blog post explaining why it is a problem, including the potential sources, contamination pathways, and human health risks. Also consider any potential equity concerns from disproportionate exposures among certain population groups. Detailed instructions will be presented in class and posted to Canvas. Blog posts of sufficient quality may be invited to be posted to Dr. Mulhern’s research blog ([www.equalwaterlab.com](http://www.equalwaterlab.com/)).

#### Capstone Project – Water Safety Planning

Following the World Health Organization’s guidance for developing a Water Safety Plan, you will research the environmental hazards and potential risks associated with the drinking water supply in your hometown (or wherever you most closely identify as your hometown). You may work independently or in pairs; if you choose to work in pairs, both students must be from or have lived in the same city or town. The idea is that you will research an area that you have personal knowledge of to build on your lived experience there. Students will go through the first five modules of the WHO’s Water Safety Plan manual. Full instructions for the capstone project will be presented in class and posted to Canvas, together with deadlines for completion. You will submit a final written Water Safety Plan and prepare a short “lightning talk” to present to the class that will serve as your final exam.

### Evaluation & Grading

You will be evaluated based on your participation in class, the blog post assignment, and the capstone project. Each of these items will be scored as outlined below. Note that your participation in class—including coming prepared having done the readings, completing the in-class writing assignments earnestly, and participating in discussions and in-class activities—is worth a significant proportion of your grade! Doing well in this class requires meaningful effort on your part into all three components:

+----------------------------------------------------+----------------------+
| ##### **Informed Participation**                   | ##### **35 points**  |
+----------------------------------------------------+----------------------+
| Office hours visit                                 | 1 point              |
+----------------------------------------------------+----------------------+
| Class attendance and active engagement             | 5 points             |
+----------------------------------------------------+----------------------+
| Graded in-class writing assignment (5 points each) | 25 points            |
+----------------------------------------------------+----------------------+
| Lead in water sample collection & analysis         | 4 points             |
+----------------------------------------------------+----------------------+
| ##### **Emerging Contaminant Blog Post**           | ##### **15 points**  |
+----------------------------------------------------+----------------------+
| ##### **Capstone Water Safety Plan (WSP)**         | ##### **50 points**  |
+----------------------------------------------------+----------------------+
| WSP Module 1 Draft - Assemble the Team             | 5 points             |
+----------------------------------------------------+----------------------+
| WSP Module 2 Draft - Describe the System           | 5 points             |
+----------------------------------------------------+----------------------+
| WSP Module 3 Draft - Identify Hazards              | 5 points             |
+----------------------------------------------------+----------------------+
| WSP Module 4 Draft - Assess Risks                  | 5 points             |
+----------------------------------------------------+----------------------+
| WSP Module 5 Draft - Improvement Plan              | 5 points             |
+----------------------------------------------------+----------------------+
| Final Written Water Safety Plan                    | 15 points            |
+----------------------------------------------------+----------------------+
| Lightning Talk Presentation                        | 10 points            |
+----------------------------------------------------+----------------------+
| ##### **TOTAL:**                                   | ##### **100 points** |
+----------------------------------------------------+----------------------+

The number of points you earn will be converted to a letter grade as follows:

| Point Total | Course Grade |
|:-----------:|:------------:|
|   93-100    |      A       |
|    90-92    |      A-      |
|    87-89    |      B+      |
|    83-86    |      B       |
|    80-82    |      B-      |
|    77-79    |      C+      |
|    73-76    |      C       |
|    70-72    |      C-      |
|    67-69    |      D+      |
|    63-66    |      D       |
|    60-62    |      D-      |
|    0-59     |      F       |

### Course Policies & Expectations

#### Attendance

Attendance is included in your course participation grade. Please come on time and prepared. You are allowed [**three**]{.underline} absences for any reason over the course of the semester – no questions asked. Please do not email me regarding your three absences. If you need to miss additional class time beyond your three allowed absences for health-related reasons or religious observations, please let me know via email before class when possible.

#### Late Work

One point will be subtracted for late submissions, with another one point subtracted for every 24 hours after the deadline. Assignments that are more than 5 days late will not be accepted. We are willing to work with you if you have a reason that makes it difficult for you to meet a deadline due to medical or religious accommodation. In these cases, please contact the professor or TA in advance to discuss your situation.

#### Email Policy

The best way to receive help in this course is to set up an appointment during my office hours. If you have specific problems or questions that cannot be addressed during office hours, an urgent matter, or need a medical or religious accommodation, please email me with “ENVS 3030” and a brief keyword or two in the subject line. I will do my best to respond promptly to student emails but please be patient. Feel free to remind me if I have not gotten back to you within 72 hours. Please also check your CU email regularly to stay up to date with all course announcements following [CU’s student email policy](https://www.colorado.edu/compliance/policies/student-e-mail-policy).

#### Devices in Class

We all struggle these days with the ways in which our devices distract us. Research shows that [distractions can significantly decrease IQ](https://www.scientificamerican.com/article/distractions-lower-our-iq/) and lead to worse academic performance. If you are in class while multitasking or checking social media, you are not actually *learning* anything at all. The technology policy in class is thus designed to support your attention to each other and the course material. Cell phones and laptops should be kept out of sight unless as directed for specific activities. If you have an academic accommodation or other specific reason that would require a device during class, I am happy to make exceptions. Please just come talk to me ahead of time. **You are strongly encouraged to keep a physical pen-and-paper notebook**. Pen and paper can’t distract you like a computer can and writing by hand has been shown to have [cognitive benefits](https://doi.org/10.17239/jowr-2015.07.02.1) that aid with memory and recall.

#### Plagiarism

All assignments for this course must be your original work. While I encourage you to talk about ideas and course materials with your classmates, all assignments must be your own. CU’s plagiarism software will automatically review online submissions to Canvas. If I determine that you have intentionally copied material from any source as if it were your own—including websites, periodicals, journals, publications, other students’ past work, **and/or AI-generated content**—you will be reported for academic dishonesty. Please see me and/or consult the resources below if you have questions about proper citation of your work to avoid plagiarism. I am happy to help with this!

-   [Harvard style guide](https://www5.open.ac.uk/library/referencing-and-plagiarism/quick-guide-to-harvard-referencing-cite-them-right) (this is a common citation style in academic environmental science journals and the citation style you will use for the capstone project)

-   [Best Practices to Avoid Plagiarism](https://owl.purdue.edu/owl/avoiding_plagiarism/best_practices.html)

-   [CU Writing Center](https://www.colorado.edu/program/writingcenter)

#### AI Policy

::: callout-important
As noted above, turning in AI-generated content as if it were your own work will be considered plagiarism. It is a waste of your efforts, your intentions, and your money to circumvent the hard work of thinking/writing for yourself. **As such, you are responsible for resisting the use of AI tools for your original writing**. At the same time, I recognize the power of AI and LLM technology as a research and learning aid. You are allowed to use AI tools such as Microsoft Copilot, Google Gemini, Chat GPT, Claude or others in the same way that you use search engines to understand scientific concepts, find new resources, or explore new topics. However, **the content generated by these tools cannot be cited**; they should always lead you to a primary source.
:::

### University Policies

In addition to the above course-specific expectations, you should be familiar with the following standard university policies.

#### Classroom Behavior

Students and faculty are responsible for maintaining an appropriate learning environment in all instructional settings, whether in person, remote, or online. Failure to adhere to such behavioral standards may be subject to discipline. Professional courtesy and sensitivity are especially important with respect to individuals and topics dealing with race, color, national origin, sex, pregnancy, age, disability, creed, religion, sexual orientation, gender identity, gender expression, veteran status, marital status, political affiliation, or political philosophy. For more information, see the [classroom behavior policy](http://www.colorado.edu/policies/student-classroom-and-course-related-behavior), the[ ](https://www.colorado.edu/sccr/student-conduct)[Student Code of Conduct](https://www.colorado.edu/sccr/media/230), and the[Office of Institutional Equity and Compliance](https://www.colorado.edu/oiec/).

#### Accommodation for Disabilities, Temporary Medical Conditions, and Medical Isolation.

If you qualify for accommodations because of a disability, please submit your accommodation letter from Disability Services to your faculty member in a timely manner so that your needs can be addressed.  Disability Services determines accommodations based on documented disabilities in the academic environment.  Information on requesting accommodations is located on the [Disability Services website](https://www.colorado.edu/disabilityservices/). Contact Disability Services at 303-492-8671 or [DSinfo\@colorado.edu](mailto:DSinfo@colorado.edu)  for further assistance.  If you have a temporary medical condition, see [Temporary Medical Conditions](https://www.colorado.edu/disabilityservices/students/temporary-medical-conditions) on the Disability Services website. If you have a temporary illness, injury or required medical isolation for which you require adjustment, please let me know via email and I will be happy to make an accommodation.

#### Prefered Names & Pronouns

CU Boulder recognizes that students' legal information doesn't always align with how they identify. Students may update their preferred names and pronouns via the student portal; those preferred names and pronouns are listed on instructors' class rosters. In the absence of such updates, the name that appears on the class roster is the student's legal name.

#### Honor Code

All students enrolled in a University of Colorado Boulder course are responsible for knowing and adhering to the[ ](https://www.colorado.edu/sccr/honor-code)[Honor Code](https://www.colorado.edu/sccr/media/229). Violations of the Honor Code may include but are not limited to: plagiarism (including use of paper writing services or technology \[such as essay bots\]), cheating, fabrication, lying, bribery, threat, unauthorized access to academic materials, clicker fraud, submitting the same or similar work in more than one course without permission from all course instructors involved, and aiding academic dishonesty. Understanding the course's syllabus is a vital part in adhering to the Honor Code. All incidents of academic misconduct will be reported to Student Conduct & Conflict Resolution: [StudentConduct\@colorado.edu](mailto:StudentConduct@colorado.edu). Students found responsible for violating the[ ](https://www.colorado.edu/sccr/honor-code)[Honor Code](https://www.colorado.edu/sccr/media/229) will be assigned resolution outcomes from the Student Conduct & Conflict Resolution as well as be subject to academic sanctions from the faculty member. Visit [Honor Code](https://www.colorado.edu/sccr/media/229) for more information on the academic integrity policy.

#### Sexual Misconduct, Discrimination, Harassment and/or Related Retaliation

CU Boulder is committed to fostering an inclusive and welcoming learning, working, and living environment. University policy prohibits [protected-class](https://www.colorado.edu/oiec/policies/discrimination-harassment-policy/protected-class-definitions) discrimination and harassment, sexual misconduct (harassment, exploitation, and assault), intimate partner abuse (dating or domestic violence), stalking, and related retaliation by or against members of our community on- and off-campus. The Office of Institutional Equity and Compliance (OIEC) addresses these concerns, and individuals who have been subjected to misconduct can contact OIEC at 303-492-2127 or email [CUreport\@colorado.edu](mailto:CUreport@colorado.edu). Information about university policies, [reporting options](https://www.colorado.edu/oiec/reporting-resolutions/making-report), and [support resources](https://www.colorado.edu/oiec/support-resources) including confidential services can be found on the [OIEC website](http://www.colorado.edu/institutionalequity/).

Please know that faculty and graduate instructors must inform OIEC when they are made aware of incidents related to these policies regardless of when or where something occurred. This is to ensure that individuals impacted receive outreach from OIEC about resolution options and support resources. To learn more about reporting and support for a variety of concerns, visit the [Don’t Ignore It](https://www.colorado.edu/dontignoreit/) [page]{.underline}.

#### Religious Accommodations

Campus policy requires faculty to provide reasonable accommodations for students who, because of religious obligations, have conflicts with scheduled exams, assignments or required attendance. Please communicate the need for a religious accommodation with me via email in a timely manner. See the [campus policy regarding religious observances](http://www.colorado.edu/policies/observance-religious-holidays-and-absences-classes-andor-exams) for full details.

#### Mental Health and Wellness

The University of Colorado Boulder is committed to the well-being of all students. If you are struggling with personal stressors, mental health or substance use concerns that are impacting academic or daily life, please contact [Counseling and Psychiatric Services (CAPS)](https://www.colorado.edu/counseling/ "https://www.colorado.edu/counseling/") located in C4C or call (303) 492-2277, 24/7. Free and unlimited telehealth is also available through [Academic Live Care](https://www.colorado.edu/health/academiclivecare "https://www.colorado.edu/health/academiclivecare"). The [Academic Live Care](https://www.colorado.edu/health/academiclivecare "https://www.colorado.edu/health/academiclivecare") site also provides information about additional wellness services on campus that are available to students.
